### ISSUE TITLE
SecureRandom.getInstanceStrong is backed by /dev/random on Linux/MacOS

### ISSUE THREAD

**Issue by codahale** [cryptosphere/sysrandom#10]
On Java 1.8.0_92, `SecureRandom.getInstanceStrong()` returns an instance which uses the `NativePRNGBlocking` algorithm, which pulls from `/dev/random`.

Would it be better to just try the `NativePRNG` algorithm and if that doesn't exist simply use the default instance? I'd be happy to put a PR together for this.

**Comment by codahale** [comment]
Sorry — I meant `NativePRNGNonBlocking`, not `NativePRNG`.

**Comment by tarcieri** [comment]
👍
