### ISSUE TITLE
Sysrandom and SecureRandom return different results for SecureRandom.random_bytes(0)

### ISSUE THREAD

**Issue by grempe** [cryptosphere/sysrandom#13]
When patching `sysrandom` over the standard `securerandom` it can return a different result in the edge case where the number of bytes requested is `0`:

```
/src$ pry
[1] pry(main)> require 'securerandom'
true
[2] pry(main)> SecureRandom.random_bytes(0)
""
[3] pry(main)> require 'sysrandom/securerandom'
true
[4] pry(main)> SecureRandom.random_bytes(0)
ArgumentError: string size is zero
from (pry):4:in `random_bytes'
```

The native implementation returns an empty string, and `sysrandom` throws an exception. For full compatibility I think `sysrandom` should also return an empty string.

**Comment by tarcieri** [comment]
If there is a real-world example of this causing a breakage, and someone demands it be fixed, I'll change it. But I think it's more likely to reveal bugs than legitimate breakages.

**Comment by grempe** [comment]
Well, it did break my test suite for the tss gem when I dropped in sysrandom today.

https://github.com/grempe/tss-rb/commit/9fb82788ebce27d4a7c644c5f51dcaf70c347018

This is a real-world usage, and I had to make what I hoped were temporary changes to the implementation due to the difference. In this case it is legitimate I believe to allow requesting a 0 byte random value on occasion, or as part of testing, as the TSS algorithm wants to handle it that way.

I would not dare 'demand' the change, but IMHO I think sysrandom should mirror the functionality of the native implementation if you are promoting it as a truly drop in replacement for it.  Otherwise you probably should not allow the monkey patch require. This way people would have to choose to use your implementation directly and would conform to your ideas of correctness, instead of how Ruby core chose to implement it.

If I flip the coin, what is the argument for raising an exception instead of returning an empty string when the empty string behavior has apparently existed in Ruby for years?

**Comment by grempe** [comment]
I was curious to see if other test suites defined this behavior. What I found was a little surprising and I'll share it with you. Most of these implementations seem to just skip over this case as far as I can tell, but they all behave the same. They return an empty string on 0 bytes requested, exception thrown only on negative numbers. I have not found any that throw an exception on 0 bytes requested except for `sysrandom`.

First, in your RbNaCl gem, you return an empty string for zero bytes requested, and only throw an exception on negatives (which I suppose is because libsodium does it that way):

```
/tmp$ irb
irb(main):001:0> require 'rbnacl'
=> true
irb(main):003:0> RbNaCl::Random.random_bytes(1)
=> "\xA5"
irb(main):004:0> RbNaCl::Random.random_bytes(0)
=> ""
irb(main):005:0> RbNaCl::Random.random_bytes(-1)
ArgumentError: negative argument
    from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rbnacl-3.4.0/lib/rbnacl/util.rb:20:in `*'
    from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rbnacl-3.4.0/lib/rbnacl/util.rb:20:in `zeros'
    from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rbnacl-3.4.0/lib/rbnacl/random.rb:23:in `random_bytes'
    from (irb):5
    from /usr/local/var/rbenv/versions/2.2.5/bin/irb:11:in `<main>'
```

Calling OpenSSL directly in Ruby returns an empty string and does not throw an exception.

```
> OpenSSL::Random.random_bytes(0)
""
```

Rubyspec did not include the zero bytes case in their tests, it looks like they start at integer `1` and _only_ throw an exception on negative numbers:

https://github.com/ruby/spec/blob/e8c46ebbf76d860a0dd50a5f45556d3bf7796ec5/library/securerandom/random_bytes_spec.rb

JRuby's specs seem to be a direct copy of the Rubyspec tests and also skips defining the behavior of 0 bytes requested:

https://github.com/jruby/jruby/blob/915993886ae6663586d893b7d237f750068aceb5/spec/ruby/library/securerandom/random_bytes_spec.rb

jruby does indeed behave the same in practice though:

```
/tmp$ jirb
irb(main):001:0> require 'securerandom'
=> true
irb(main):002:0> SecureRandom.random_bytes(0)
=> ""

irb(main):003:0> SecureRandom.random_bytes(-1)
ArgumentError: negative argument: -1
    from org/jruby/ext/securerandom/SecureRandomLibrary.java:21:in `random_bytes'
    from (irb):3:in `<eval>'
    from org/jruby/RubyKernel.java:976:in `eval'
    from org/jruby/RubyKernel.java:1287:in `loop'
    from org/jruby/RubyKernel.java:1096:in `catch'
    from org/jruby/RubyKernel.java:1096:in `catch'
    from /usr/local/var/rbenv/versions/jruby-9.0.5.0/bin/jirb:13:in `<top>'
```

Out of curiosity I checked what Python does in this case. It seems to do the same as all the rest, it returns an empty string when zero bytes requested, and an exception only on negatives:

```
~/src$ python --version
Python 2.7.12 (default, Jun 29 2016, 14:05:02)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.urandom(0)
''
>>> os.urandom(1)
'q'
>>> os.urandom(-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: negative argument not allowed
>>>
```

And an alternative in python which reads direct from urandom requesting zero bytes also returns empty string:

```
>>> open("/dev/urandom","rb").read(0)
''
```

Since as far as I can tell there is not a method that returns a random byte string in Python I looked elsewhere for how they do it.  I found this third party lib that provides that functionality.

https://github.com/StorjOld/RandomIO

It behaves the same:

```
/tmp/RandomIO (master ✔)$ python
Python 2.7.12 (default, Jun 29 2016, 14:05:02)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import RandomIO
>>> s = RandomIO.RandomIO()
>>> print(s.read(10))
t_UC�q�]
>>> print(s.read(0))

>>>
```

This lib did have an explicit test for requesting to read zero bytes and it expects a 0 length string to be returned:

https://github.com/StorjOld/RandomIO/blob/master/tests/test_unit.py#L150

I hope this is useful in your decision making on this particular issue.

**Comment by tarcieri** [comment]
Ok, since this seems to be causing real-world breakages let's change it to match the stdlib behavior.

**Comment by grempe** [comment]
I'm working on a pull request now.

**Comment by grempe** [comment]
PR submitted, and I added a second commit that brings in some specs from rubyspec/jruby just to ensure that everything they test for is also covered here.

**Comment by grempe** [comment]
Awesome! Thanks for merging Tony. If you could cut a new release that would be great.
