### ISSUE TITLE
ArgumentError (wrong number of arguments (2 for 0..1)):

### ISSUE THREAD

**Issue by luckyraul** [cryptosphere/sysrandom#15]
ArgumentError (wrong number of arguments (2 for 0..1)):
  
sysrandom (1.0.3) lib/sysrandom.rb:56:in `urlsafe_base64'

**Comment by tarcieri** [comment]
The second argument is a newly-added Ruby 2.3 feature (one I was actually involved in, so shame on me for not supporting it)

I can add it.

**Comment by luckyraul** [comment]
It's actually available from 2.0 =)

https://ruby-doc.org/stdlib-2.0.0/libdoc/securerandom/rdoc/SecureRandom.html

**Comment by tarcieri** [comment]
Apparently it was the `Base64` module itself which didn't get it until 2.3: https://ruby-doc.org/stdlib-2.3.1/libdoc/base64/rdoc/Base64.html#method-i-urlsafe_encode64

**Comment by tarcieri** [comment]
Fix released as 1.0.4
